config/routes.rb
Rails.application.routes.draw do
  resources :sessions
  root to: "home#index"
  get "users/me" => "users#me"
  resources :users do 
  	member do
  		get 'widgets'
  	end
  end

  resources :widgets

  resource :session, only: [:new, :create, :destroy]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  	search_query = params[:val] || ''
  	@widgets = Widget.all("visible",search_query, current_user)
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_index.html.erb
<div id= "widgets">
	<div class = "row">
    <%@widgets.each do |widget|%>
    	<div class = "col-lg-4 mt-20" style = "margin-bottom: 10px"> 
				<div class="card bg-light" style="width: 18rem;">
			  	<div class= "card-header">
			    	<h5 class="card-title"><%= widget.name%></h5>
			    </div>
				  <div class="card-body bg-light">
					  <p class= "card-text" style = "font-family: 'Calibri','Slate Pro','sans-serif' !important; color:#262626; font-size: 16px!important "><%=widget.description%></p>
				  </div>
				  <div class = "card-footer">
				    <p>by <a href=<%= "/users/#{widget.user[:id]}/widgets"%> class="card-link"><%= image_tag widget.user[:images][:small_url], class: "img-circle", height:"30", width:"30" %><%= widget.user[:name]%></a> </p>
				  </div>

				  <% if widget.owner %>
				  	<button class = "btn btn-primary" data-toggle="modal" data-target = <%= "#widgetEditModal#{widget.id}"%> >Edit</button>
							<div class="container">
							  <!-- The Modal -->
							  <div class="modal" id=<%="widgetEditModal#{widget.id}"%>>
							    <div class="modal-dialog">
							      <div class="modal-content">
							      
							        <!-- Modal Header -->
							        <div class="modal-header">
							          <h4 class="modal-title">Widget</h4>
							          <button type="button" class="close" data-dismiss="modal">&times;</button>
							        </div>
							        
							        <!-- Modal body -->
							        <div class="modal-body">
												<%= simple_form_for(widget, :url => widget_path(widget.id), method: :put, wrapper: :vertical_form) do |f| %>
												  <%= f.error_notification %>
												  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

												  <div class="form-inputs">
												    <%= f.input :name, required: true %>
												    <%= f.input :description, required: true %>
												  	<%= f.input :kind, :collection => [['visible','visible'],['hidden', 'hidden']], required: true %>
												  </div>

												  <div class="form-actions">
												    <%= f.button :submit, "Update Widget", class:"btn-primary" %>
												  </div>
												<% end %>

							        </div>
							        
							      </div>
							    </div>
							  </div>
							</div>
				  	  <%= link_to 'Delete', widget_path(widget.id), class: "btn btn-danger", method: :delete %>
				  <% end %>
				</div>
			</div>
    <%end%>
	</div>
</div>

app/views/home/index.html.erb
<div class = "jumbotron">
	<div class= "row">
	  <div class = "col-sm-10">
      <h2>Widgets</h2>
			<form class="form-inline active-cyan-4" id="search_form" style = "margin: 30px">
			  <input class="form-control form-control-sm mr-3 w-75" id = "search_input" type="text" placeholder="Search"
			    aria-label="Search">

			  <i class="fa fa-search" id = "search_button"></i>
			</form>
				<%= render "home/index"%>
	 	 </div>
	  <div class = "col-sm-2">
	    <a href = "/widgets/new"><button type="button" class="btn btn-success">Create Widget</button></a>
	  </div>
	</div>
</div>

app/views/home/index.js.erb
$('#widgets').html("<%=  escape_javascript(render(:partial => 'index'))%>");